# 01_clean: turn raw survey codes into an analysis-ready dataset
Input: data/raw/ · Output: data/processed/clean.csv

## 1. Load

In [45]:
import pandas as pd

# -- Load raw data --
# survey microdata: one row per respondent
df = pd.read_csv("../data/raw/polling_on_ai_usage_jul_2026_microdata.csv").copy()

# Epoch's published summary tables: used to check our cleaning
summary = pd.read_csv("../data/raw/polling_on_ai_usage_jul_2026.csv")

print("Microdata:", df.shape)
print("Summary table:", summary.shape)

Microdata: (1103, 333)
Summary table: (3008, 13)

## 2. Demographics

In [46]:
# -- Split Age Groups so it matches Epoch summary table --
df["age_group"] = pd.cut(
    df["ppage"],
    bins=[17, 29, 44, 59, 120],
    labels=["18-29", "30-44", "45-59", "60+"]
)

# counts per group, in order
df["age_group"].value_counts().sort_index()

age_group
18-29    232
30-44    382
45-59    312
60+      177
Name: count, dtype: int64

In [47]:
# Check age groups against Epoch
epoch_age = summary.loc[
    (summary["demographic"] == "age_group") & (summary["question"] == "q2_services"),
    ["demographic_value", "n_base"]
].drop_duplicates() #remove repeats

epoch_age

    demographic_value  n_base
295             18–29     232
304             30–44     382
313             45–59     312
322               60+     177

✅ Age groups match Epoch's n_base exactly.

In [48]:
# -- Education: give the codes readable levels --
edu_labels = {1: "Less than HS", 2: "High school", 3: "Some college", 4: "Bachelor+"}
df["education"] = df["ppeducat"].map(edu_labels)

# college(yes) is considered bachelors degree or higher
df["college"] = df["ppeducat"] == 4

# our counts per education label
print(df["education"].value_counts())

# Epoch count per education label
summary.loc[
    (summary["demographic"] == "education") & (summary["question"] == "q2_services"),
    ["demographic_value", "n_base"]
].drop_duplicates()

education
Bachelor+       470
High school     284
Some college    281
Less than HS     68
Name: count, dtype: int64

    demographic_value  n_base
421      Less than HS      68
430       High school     284
439      Some college     281
448         Bachelor+     470

In [49]:
# -- Income -- 
# Version 1: Epoch's 5 groups --> tables, tool, validation
income_labels = {1: "Under $25K", 2: "Under $25K", 3: "$25K–$50K", 4: "$50K–$75K",
                 5: "$75K–$100K", 6: "$100K+", 7: "$100K+"}
df["income"] = df["ppinc7"].map(income_labels)

# Version 2: same but the top group is split since it holds 57% of sample --> used for regression!
income_reg_labels = {1: "Under $25K", 2: "Under $25K", 3: "$25K–$50K", 4: "$50K–$75K",
                     5: "$75K–$100K", 6: "$100K–$150K", 7: "$150K+"}
df["income_reg"] = df["ppinc7"].map(income_reg_labels)

# -- Race/ethnicity -- 
# Epoch's 4 groups
race_labels = {1: "White, Non-Hispanic", 2: "Black, Non-Hispanic", 3: "Other/2+, Non-Hispanic",
               4: "Hispanic", 5: "Other/2+, Non-Hispanic"}
df["race"] = df["ppethm"].map(race_labels)

# -- Gender -- 
gender_labels = {1: "Male", 2: "Female"}
df["gender"] = df["ppgender"].map(gender_labels)

# Check against Epoch
for ours, theirs in [("income", "income"), ("race", "race_ethnicity"), ("gender", "gender")]:
    print("OURS:", ours)
    print(df[ours].value_counts())
    print("EPOCH:")
    print(summary.loc[
        (summary["demographic"] == theirs) & (summary["question"] == "q2_services"),
        ["demographic_value", "n_base"]
    ].drop_duplicates())
    print("-" * 40)

OURS: income
income
$100K+        634
$50K–$75K     142
$75K–$100K    139
$25K–$50K     109
Under $25K     79
Name: count, dtype: int64
EPOCH:
    demographic_value  n_base
457        Under $25K      79
466         $25K–$50K     109
475         $50K–$75K     142
484        $75K–$100K     139
493            $100K+     634
----------------------------------------
OURS: race
race
White, Non-Hispanic       666
Hispanic                  191
Black, Non-Hispanic       140
Other/2+, Non-Hispanic    106
Name: count, dtype: int64
EPOCH:
          demographic_value  n_base
349     White, Non-Hispanic     666
358     Black, Non-Hispanic     140
367                Hispanic     191
376  Other/2+, Non-Hispanic     106
----------------------------------------
OURS: gender
gender
Male      593
Female    510
Name: count, dtype: int64
EPOCH:
    demographic_value  n_base
331              Male     593
340            Female     510
----------------------------------------

## 3. Job Groups

In [50]:
# -- Job Groups: Q26 code --> 5 groups(overall results + regression) --
job_labels = {
    # Office/Knowledge
    1: "Office/knowledge", 30: "Office/knowledge", 31: "Office/knowledge", 3: "Office/knowledge",
    4: "Office/knowledge", 5: "Office/knowledge", 7: "Office/knowledge", 33: "Office/knowledge",
    22: "Office/knowledge",
    # Sales/service
    35: "Sales/service", 16: "Sales/service", 17: "Sales/service", 18: "Sales/service", 15: "Sales/service",
    # Manual/trades
    23: "Manual/trades", 24: "Manual/trades", 25: "Manual/trades", 26: "Manual/trades", 27: "Manual/trades",
    # Healthcare
    34: "Healthcare", 13: "Healthcare", 14: "Healthcare",
    # Education & social services
    32: "Education & social services", 6: "Education & social services",
}

# codes not in dictionary(29 other, 28 Armed forces, -1 refused) --> NaN
df["job_group"] = df["Q26"].map(job_labels)

# -- 3 Broad groups built from the 5 groups (age x job tables + tool) --
broad_labels = {
    "Office/knowledge": "Office/knowledge",
    "Healthcare": "Care & education",
    "Education & social services": "Care & education",
    "Sales/service": "Frontline",
    "Manual/trades": "Frontline",
}
df["job_broad"] = df["job_group"].map(broad_labels)

# Check
print(df["job_group"].value_counts(dropna=False))
pd.crosstab(df["job_broad"], df["age_group"])

job_group
Office/knowledge               433
Sales/service                  220
Manual/trades                  134
NaN                            120
Education & social services    104
Healthcare                      92
Name: count, dtype: int64

age_group         18-29  30-44  45-59  60+
job_broad
Care & education     43     68     57   28
Frontline           103    103     92   56
Office/knowledge     63    172    130   68

## 4. Outcome Variables
ai_any = used any AI service in past week
ai_work = used AI at least partly for work (Q5 codes 1-4)

In [51]:
# -- Col lists: Q2_1 ~ Q2_9 = 9 AI services (9 = 'Other'); Q5 = how each was used --
q2_cols = [f"Q2_{i}" for i in range(1, 10)]
q5_cols = [f"Q5_{i}" for i in range(1, 10)]

df["ai_any"] = (df[q2_cols] == 1).any(axis=1).astype(float)

df["ai_work"] = df[q5_cols].isin([1,2,3,4]).any(axis=1).astype(float)

refused_q2 = (df[q2_cols + ["Q2_10"]] == -1).all(axis=1)
df.loc[refused_q2, ["ai_any", "ai_work"]] = None

# Checks
print(df["ai_any"].value_counts(dropna=False))
print(df["ai_work"].value_counts(dropna=False))
pd.crosstab(df["ai_any"], df["ai_work"])

ai_any
1.0    605
0.0    497
NaN      1
Name: count, dtype: int64
ai_work
0.0    633
1.0    469
NaN      1
Name: count, dtype: int64

ai_work  0.0  1.0
ai_any
0.0      497    0
1.0      136  469

## 5. Validation: weighted % vs Epoch's publichsed numbers
weighted_pct() = weighted % of 1s in a 0/1 column --> must match Epoch's published pct within 1 percentage point

In [52]:
import sys
sys.path.append("..")
from src.helpers import weighted_pct

# Validation
print("All:", round(100 - weighted_pct(df, "ai_any"), 2))
for group in ["18-29", "30-44", "45-59", "60+"]:
    subgroup = df[df["age_group"] == group]
    print(group, round(100 - weighted_pct(subgroup, "ai_any"), 2))

# Epoch pubclished numbers
summary.loc[
    (summary["question"] == "q2_services") & (summary["response"] == "None (no AI use)")
    & (summary["demographic"].isin(["full_sample", "age_group"])),
    ["demographic_value", "pct", "ci_lo", "ci_hi"]
]

All: 44.64
18-29 41.62
30-44 39.45
45-59 47.72
60+ 56.58

    demographic_value    pct  ci_lo  ci_hi
294               All  44.61  42.14  47.10
303             18–29  41.62  36.39  47.04
312             30–44  39.36  35.32  43.55
321             45–59  47.72  43.09  52.38
330               60+  56.58  50.38  62.58

✅ Matches Epoch within 0.1 percentage points (overall and all 4 age groups).
Tiny differences come from 1 respondent who refused Q2: Epoch kept them in the base; we excluded them.

## 6. Task level time (for Q2)

In [53]:
# --- Task names, in the survey's order ---
task_names = {1: "Maintaining records", 2: "Developing policies/processes", 3: "Reading documents",
              4: "Determining values/prices", 5: "Analyzing data", 6: "Designing systems/apps",
              7: "Preparing documentation", 8: "Explaining info to clients",
              9: "Advising on business", 10: "Assessing students"}

# person level cols to carry along to every task row
keep = ["CaseID", "weight", "age_group", "college", "education", "job_group", "job_broad",
        "gender", "income_reg", "race"]

# build one small table per task, then stack
pieces = []
for k in range(1, 11):
    piece = df[keep].copy()         #person info on everyone
    piece["task"] = task_names[k]   #which task this piece is about
    piece["before"] = df[f"Q13_{k}"] #hours range BEFORE AI for task 'k'
    piece["now"] = df[f"Q11_{k}"]   # hours range NOW for task k
    pieces.append(piece)

tasks = pd.concat(pieces) 
tasks = tasks[tasks["now"].notna()]

# Checks
print("Task reports:", tasks.shape[0], "| People:", tasks["CaseID"].nunique())
tasks.head()

Task reports: 798 | People: 317

,CaseID,weight,age_group,college,education,job_group,job_broad,gender,income_reg,race,task,before,now
24,241,0.9479,30-44,True,Bachelor+,Office/knowledge,Office/knowledge,Male,$150K+,"White, Non-Hispanic",Maintaining records,3.0,1.0
56,1053,0.8084,60+,True,Bachelor+,Education & social services,Care & education,Female,$75K–$100K,"White, Non-Hispanic",Maintaining records,3.0,2.0
95,408,0.9479,30-44,True,Bachelor+,Office/knowledge,Office/knowledge,Male,$150K+,"White, Non-Hispanic",Maintaining records,2.0,2.0
97,573,1.0117,30-44,False,Some college,Office/knowledge,Office/knowledge,Male,$100K–$150K,"Other/2+, Non-Hispanic",Maintaining records,1.0,1.0
201,712,0.8701,30-44,True,Bachelor+,Office/knowledge,Office/knowledge,Male,$100K–$150K,"White, Non-Hispanic",Maintaining records,4.0,3.0

In [54]:
# -- Label each task report -- 
def classify_change(row):
    """
    Label one task report by comparing hours range before and now 
    Codes 1-5 = hour ranges; 6 = not sure; 7 = didn't do this task before AI; -1 = refused
    Returns: "New task", "Not sure/refused", "Less time", "Same", or "More time"
    """

    if row["before"] == 7:
        return "New task"
    if row["before"] in [6, -1] or row["now"] in [6, -1]:
        return "Not sure/refused"
    if row["now"] < row["before"]:
        return "Less time"
    if row["now"] == row["before"]:
        return "Same"
    return "More time"

tasks["change"] = tasks.apply(classify_change, axis="columns")

# Check
tasks["change"].value_counts()

change
Same                322
Less time           281
More time           117
Not sure/refused     57
New task             21
Name: count, dtype: int64

### 6b. Person-level: net time saver
Net time-saver = more tasks got faster than slower(comparable tasks only)

people with no comparable tasks = missing, not "no"

In [55]:
# 1. Keep only comparable task reports
comparable = tasks[tasks["change"].isin(["Less time", "Same", "More time"])].copy()

# 0/1 flags so we can count by adding
comparable["is_less"] = (comparable["change"] == "Less time").astype(int)
comparable["is_more"] = (comparable["change"] == "More time").astype(int)

# 2. Per person: how many tasks got faster vs slower
per_person = comparable.groupby("CaseID")[["is_less", "is_more"]].sum()

# 3. Net time saver = more faster tasks than slower tasks
per_person["net_saver"] = (per_person["is_less"] > per_person["is_more"]).astype(float)

# Attach to df by CaseID; people with no comparable tasks get NaN
df["net_saver"] = df["CaseID"].map(per_person["net_saver"])

# --- 3 way version: separates "no change" from "net slower" ---
per_person["net_status"] = "No change"
per_person.loc[per_person["is_less"] > per_person["is_more"], "net_status"] = "Net saver"
per_person.loc[per_person["is_less"] < per_person["is_more"], "net_status"] = "Net slower"

df["net_status"] = df["CaseID"].map(per_person["net_status"])

# Check
print(per_person["net_status"].value_counts())
print(pd.crosstab(per_person["net_status"], per_person["net_saver"]))


# Checks
print("People with at least 1 comparable task:", len(per_person))
print("People with only new/not sure tasks(excluded):", tasks["CaseID"].nunique() - len(per_person))
per_person.head()

net_status
No change     117
Net saver     114
Net slower     53
Name: count, dtype: int64
net_saver   0.0  1.0
net_status
Net saver     0  114
Net slower   53    0
No change   117    0
People with at least 1 comparable task: 284
People with only new/not sure tasks(excluded): 33

        is_less  is_more  net_saver net_status
CaseID
6             0        0        0.0  No change
9             0        0        0.0  No change
15            0        0        0.0  No change
17            0        0        0.0  No change
18            3        0        1.0  Net saver

## 7. BLS Exposure (For Q3)

In [56]:
bls_file = "../data/raw/ai-exposure-categories.xlsx"
xls = pd.ExcelFile(bls_file)
print(xls.sheet_names)

['AI Exposure Categories', 'Field Descriptions']

In [57]:
# Read codebook sheet exactly as is
fields = pd.read_excel(bls_file, sheet_name="Field Descriptions", header=None)

# show full text in each cell
pd.set_option("display.max_colwidth", None)

fields

,0,1,2
0,"AI Exposure Categories and Employment Projections, 2025–35",NaN,NaN
1,"BLS employment projections are intended to capture long-term structural changes in the labor market. Assessing potential impacts of new and emerging technologies, including artificial intelligence (AI), is an area of focus for the BLS Employment Projections (EP) program. \n\nThis supplemental table provides information about how occupations compare to one another based on their theoretical and observed exposure to AI. BLS combined five publicly available data sources to create a four-category classification of relative AI exposure for detailed occupations. Exposure signifies that AI technology could be or has been used to assist or complete some of the work performed in an occupation. Exposure does not imply job loss, productivity gains, automation probability, or wage effects. See https://www.bls.gov/emp/publications/ai-exposure-categories.htm for additional information and limitations.",NaN,NaN
2,Employment Projections Program,NaN,NaN
3,"Bureau of Labor Statistics, Department of Labor",NaN,NaN
4,website: https://www.bls.gov/emp,NaN,NaN
5,phone: 202-691-5700,NaN,NaN
6,NaN,NaN,NaN
7,NaN,NaN,NaN
8,NaN,NaN,NaN
9,Field,Field Description,Format
10,2025 National Employment Matrix title,SOC-based occupation title,Text
11,2025 National Employment Matrix code,SOC-based occupation code,6-digit code
12,"Employment, 2025","Employment in thousands of jobs, in 2025","Number of jobs in thousands, rounded to nearest hundred"
13,"Employment, 2035","Employment in thousands of jobs, in 2035","Number of jobs in thousands, rounded to nearest hundred"
14,"Employment change, numeric, 2025–35",Employment in 2035 minus employment in 2025,"Number of jobs in thousands, rounded to nearest hundred"
15,"Employment change, percent, 2025–35",Numeric change divided by employment in 2025,"Percent, rounded to 1 decimal"
16,"Percent self employed, 2025",Percent of occupation that is self employed,"Percent, rounded to 1 decimal"
17,"Occupational openings, 2025–35 annual average",Annual average of occupational openings from 2025–35,"Number of jobs in thousands, rounded to nearest hundred"
18,"Median annual wage, dollars, 2025",Median annual wage data from 2025,"Dollars, rounded to the nearest 10"
19,Typical education needed for entry,"Education level by detailed occupation (No formal educational credential; High school diploma or equivalent; Some college, no degree; Postsecondary nondegree award; Associate's degree; Bachelor's degree; Master's degree; Doctoral or professional degree)",Text
20,Work experience in a related occupation,Work experience by detailed occupation (None; Less than 5 years; 5 years or more),Text
21,Typical on-the-job training needed to attain competency in the occupation,On-the-job training by detailed occupation (None; Short-term on the job training; Moderate-term on-the-job training; Long-term on-the-job training; Apprenticeship; Internship/residency),Text
22,Relative AI exposure,"Relative AI exposure category (Low, Moderate, High, Very high)",Text
23,NaN,NaN,NaN
24,Note:,NaN,NaN
25,"Wage data are from the Occupational Employment and Wage Statistics program. The wage data cover non-farm wage and salary workers and do not cover the self-employed, owners and partners in unincorporated firms, or household workers.",NaN,NaN

In [58]:
# Peek at data sheet
bls_raw = pd.read_excel(bls_file, sheet_name="AI Exposure Categories", header=None)
print(bls_raw.shape)
bls_raw.head(10)

(838, 13)

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,AI exposure categories and 2025–35 employment projections (Employment in thousands),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2025 National Employment Matrix title,2025 National Employment Matrix code,"Employment, 2025","Employment, 2035","Employment change, numeric, 2025–35","Employment change, percent, 2025–35","Percent self-employed, 2025","Occupational openings, 2025–35, annual average","Median annual wage, dollars, 2025",Typical education needed for entry,Work experience in a related occupation,Typical on-the-job training needed to attain competency in the occupation,Relative AI exposure
2,Chief executives,11-1011,291.6,300.9,9.3,3.2,26.6,19.1,213990,Bachelor's degree,5 years or more,NaN,Very high
3,General and operations managers,11-1021,3599,3780.3,181.3,5,0.8,285,105770,Bachelor's degree,5 years or more,NaN,High
4,Advertising and promotions managers,11-2011,33.2,31.9,-1.2,-3.7,35.1,2.3,133660,Bachelor's degree,Less than 5 years,NaN,Very high
5,Marketing managers,11-2021,421.6,450.8,29.1,6.9,5.3,34,166790,Bachelor's degree,5 years or more,NaN,Very high
6,Sales managers,11-2022,650.1,679.1,29,4.5,0.8,47.3,148270,Bachelor's degree,Less than 5 years,NaN,High
7,Public relations managers,11-2032,80.8,85.4,4.6,5.7,0.4,6.1,146910,Bachelor's degree,5 years or more,NaN,Very high
8,Fundraising managers,11-2033,48.8,51.4,2.6,5.4,0.3,3.7,125470,Bachelor's degree,5 years or more,NaN,High
9,Administrative services managers,11-3012,279,293.3,14.4,5.2,1,22,114130,Bachelor's degree,Less than 5 years,NaN,Moderate

In [59]:
# Reload
bls = pd.read_excel(bls_file, sheet_name="AI Exposure Categories", header=1)
print(bls.shape)
bls.tail(8)

(836, 13)

,2025 National Employment Matrix title,2025 National Employment Matrix code,"Employment, 2025","Employment, 2035","Employment change, numeric, 2025–35","Employment change, percent, 2025–35","Percent self-employed, 2025","Occupational openings, 2025–35, annual average","Median annual wage, dollars, 2025",Typical education needed for entry,Work experience in a related occupation,Typical on-the-job training needed to attain competency in the occupation,Relative AI exposure
828,Refuse and recyclable material collectors,53-7081,156.4,159.6,3.2,2.1,3.8,15.5,49690,No formal educational credential,NaN,Short-term on-the-job training,Low
829,"Tank car, truck, and ship loaders",53-7121,12.8,13.2,0.4,2.8,14.8,1.3,58870,No formal educational credential,NaN,Short-term on-the-job training,Low
830,"Material moving workers, all other",53-7199,27.8,28.6,0.8,2.7,13.7,2.8,41800,No formal educational credential,NaN,Short-term on-the-job training,Low
831,Note:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
832,"Exposure signifies that AI technology could be or has been used to assist or complete some of the work performed in an occupation. Exposure does not imply job loss, productivity gains, automation probability, or wage effects.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
833,"Wage data are from the Occupational Employment and Wage Statistics program. The wage data cover non-farm wage and salary workers and do not cover the self-employed, owners and partners in unincorporated firms, or household workers.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
834,"Data is unavailable for values denoted with a ""—"".",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
835,Source: U.S. Bureau of Labor Statistics.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [60]:
# Pick our 4 columns by position: 0 title, 1 code, 2 employment 2025, 12 AI Exposure 
keep_cols = bls.columns[[0,1,2,12]]
print(list(keep_cols))

bls = bls[keep_cols].copy()
bls.columns = ["title", "soc_code", "employment_2025", "exposure"]

bls = bls[bls["soc_code"].notna()]

# checks
print(bls.shape)
print(bls["employment_2025"].dtype)
print(bls["exposure"].value_counts(dropna=False))

['2025 National Employment Matrix title', '2025 National Employment Matrix code', 'Employment, 2025', 'Relative AI exposure']
(831, 4)
float64
exposure
Low          213
Very high    206
High         206
Moderate     206
Name: count, dtype: int64

### 7b. Match survey job codes to BLS codes

In [63]:
# Distinct survey job codes
q261 = df["Q261"].dropna()
q261 = q261[q261 > 0].astype(int).astype(str)
codes = pd.DataFrame({"q261": q261.unique()})

# convert to BLS style
codes["soc"] = codes["q261"].str[:2] + "-" + codes["q261"].str[2:]

# Step 1 of funnel: does the exact code exist in BLS?
bls["soc_code"] = bls["soc_code"].astype(str).str.strip()
codes["exact"] = codes["soc"].isin(bls["soc_code"])

# Checks
print("Distinct survey codes:", len(codes))
print("Exact matches:", codes["exact"].sum())
codes.head(10)

Distinct survey codes: 139
Exact matches: 18

     q261      soc  exact
0  272020  27-2020  False
1  111020  11-1020  False
2  291140  29-1140  False
3  413090  41-3090  False
4  113020  11-3020  False
5  433000  43-3000  False
6  436000  43-6000  False
7  412010  41-2010  False
8  371010  37-1010  False
9  259090  25-9090  False

In [66]:
# Group match
# Prefix = code with trailing 0s removed
codes["prefix"] = codes["soc"].str.rstrip("0")

# how many BLS occupations start with each prefix?
codes["n_bls"] = codes["prefix"].apply(lambda p: bls["soc_code"].str.startswith(p).sum())

# How many survey respondents have ach code?
codes["n_people"] = codes["q261"].map(q261.value_counts())

# Checks
print("Codes with at elast 1 BLS match:", (codes["n_bls"] > 0).sum())
print("Codes with NO match(leftovers):", (codes["n_bls"] == 0).sum())
codes[codes["n_bls"] == 0].sort_values("n_people", ascending=False)

Codes with at elast 1 BLS match: 124
Codes with NO match(leftovers): 15

       q261      soc  exact   prefix  n_bls  n_people
38   311010  31-1010  False   31-101      0        17
28   151190  15-1190  False   15-119      0        14
19   151132  15-1132  False  15-1132      0        13
16   151121  15-1121  False  15-1121      0        10
83   433400  43-3400  False    43-34      0        10
14   151142  15-1142  False  15-1142      0         8
65   151133  15-1133  False  15-1133      0         8
127  291190  29-1190  False   29-119      0         6
61   151151  15-1151  False  15-1151      0         5
77   291060  29-1060  False   29-106      0         5
86   151122  15-1122  False  15-1122      0         5
114  151141  15-1141  False  15-1141      0         5
72   151110  15-1110  False   15-111      0         3
94   151131  15-1131  False  15-1131      0         2
116  151134  15-1134  False  15-1134      0         2

### 7c. Hand map leftover codes
15 survey codes did not match BLS. Most are old 2010 SOC codes that were renumbered in 2018

Mapped by hand using the official 2010 -> 2018 SOC crosswalk

In [68]:
# Leftover survey code --> list of BLS code prefixes to match on
hand_map = {
    "151110": ["15-1221"],             # Computer & info research scientists
    "151121": ["15-1211"],             # Computer systems analysts
    "151122": ["15-1212"],             # Information security analysts
    "151131": ["15-1251"],             # Computer programmers
    "151132": ["15-1252"],             # Software developers (applications)
    "151133": ["15-1252"],             # Software developers (systems), merged in 2018
    "151134": ["15-1254"],             # Web developers
    "151141": ["15-1242"],             # Database administrators
    "151142": ["15-1244"],             # Network & computer systems admins
    "151151": ["15-1232"],             # Computer user support specialists
    "151190": ["15-1299"],             # Computer occupations, all other
    "311010": ["31-112", "31-113"],    # Home health/personal care aides + nursing assistants
    "291060": ["29-121", "29-124"],    # Physicians + surgeons
    "291190": ["29-129"],              # Other health diagnosing/treating
    "433400": ["43-4"],                # Typo: 43-3400 doesn't exist; 43-4 = info & record clerks
}

def get_prefixes(row):
    """ Return the BLS prefixes for one survey code """
    if row["q261"] in hand_map:
        return hand_map[row["q261"]]
    return [row["prefix"]]

codes["prefixes"] = codes.apply(get_prefixes, axis="columns")

def count_bls(prefixes):
    """ Count BLS occupations whose code starts with ANY of these prefixes """
    return bls["soc_code"].str.startswith(tuple(prefixes)).sum() 

codes["n_bls"] = codes["prefixes"].apply(count_bls)

# Check
print("Codes still unmatched:", (codes["n_bls"] == 0).sum())
print(codes[codes["q261"].isin(hand_map)][["q261", "prefixes", "n_bls", "n_people"]])

Codes still unmatched: 0
       q261          prefixes  n_bls  n_people
14   151142         [15-1244]      1         8
16   151121         [15-1211]      1        10
19   151132         [15-1252]      1        13
28   151190         [15-1299]      1        14
38   311010  [31-112, 31-113]      4        17
61   151151         [15-1232]      1         5
65   151133         [15-1252]      1         8
72   151110         [15-1221]      1         3
77   291060  [29-121, 29-124]     12         5
83   433400            [43-4]     17        10
86   151122         [15-1212]      1         5
94   151131         [15-1251]      1         2
114  151141         [15-1242]      1         5
116  151134         [15-1254]      1         2
127  291190          [29-129]      3         6

### 7d. One rating per survey code
Many survey codes cover several BLS jobs with different ratings. Rule: the code gets the rating that covers the most workers(2025 employment). 'bls_conf' = share of workers that rating covers (1 = every matched job agrees)

In [69]:
def assign_rating(prefixes):
    """ For one survey code: find its BLS jobs, add up workeres per exposure rating
    and return the top rating plus the share of workers it covers """
    match = bls[bls["soc_code"].str.startswith(tuple(prefixes))]
    workers = match.groupby("exposure")["employment_2025"].sum()
    if workers.sum() == 0:
        workers = match["exposure"].value_counts()
    top = workers.idxmax()
    share = workers.max() / workers.sum()
    return pd.Series({"bls_exposure": top, "bls_conf": share})

    
# Run it on every survey code
codes[["bls_exposure", "bls_conf"]] = codes["prefixes"].apply(assign_rating)

# Checks
print("Ratings across the 139 codes:")
print(codes["bls_exposure"].value_counts(), "\n")
print("Confidence summary:")
print(codes["bls_conf"].describe(), "\n")

# Least confident codes, to eyeball (not a cutoff rule, just a look)
print(codes.sort_values("bls_conf")
           [["q261", "n_bls", "bls_exposure", "bls_conf", "n_people"]]
           .head(15))

Ratings across the 139 codes:
bls_exposure
Very high    54
High         41
Moderate     28
Low          16
Name: count, dtype: int64

Confidence summary:
count    139.000000
mean       0.945231
std        0.125270
min        0.367131
25%        0.992726
50%        1.000000
75%        1.000000
max        1.000000
Name: bls_conf, dtype: float64

       q261  n_bls bls_exposure  bls_conf  n_people
105  271020      8    Very high  0.367131         1
48   435000     11         High  0.371338         3
76   292050      6         High  0.509877         2
129  232090      2         High  0.543636         1
69   271010      5    Very high  0.571079        10
91   112020      2         High  0.606606         3
75   211010      5         High  0.660093         2
52   172070      2         High  0.670359         2
118  191020      4    Very high  0.705357         1
77   291060     12         High  0.718579         5
89   272010      2         High  0.728370         1
38   311010      4     Moderate  0.745628        17
125  272040      2     Moderate  0.769300         2
39   352010      6     Moderate  0.780952        10
85   291120      8         High  0.781758         5

## 8. Save

In [61]:
# -- Save the cleaned datasets for 02_analysis --

df.to_csv("../data/processed/clean.csv", index=False)
tasks.to_csv("../data/processed/tasks.csv", index=False)

print("clean.csv:", df.shape)
print("tasks.csv:", tasks.shape)

clean.csv: (1103, 346)
tasks.csv: (798, 14)